
platform :ios, '10.0'

use_frameworks!

def shared_pods
    
end

target 'SatelliteStoreSwift' do
    shared_pods
end

target 'SatelliteStoreSwiftTests' do
    pod 'Quick'
    pod 'Nimble'
end

target 'SatelliteStoreSwiftUITests' do
    pod 'Nimble'
    pod 'Quick'
end
